DROP TABLE IF EXISTS Dresseur;
DROP TABLE IF EXISTS Pokemon;
DROP TABLE IF EXISTS DresseurPokemon;

CREATE SEQUENCE "POKEMON_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE Pokemon (
    id BIGINT NOT NULL DEFAULT nextval('POKEMON_SEQ') PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    xp INTEGER NOT NULL,
    life_Point INTEGER NOT NULL,
    combat_Point INTEGER NOT NULL
);

CREATE SEQUENCE "DRESSEUR_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE Dresseur (
    id BIGINT NOT NULL DEFAULT nextval('DRESSEUR_SEQ'),
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE DresseurPokemon (
    dresseurId BIGINT NOT NULL,
    pokemonId BIGINT NOT NULL,
    PRIMARY KEY (dresseurId, pokemonId),
    FOREIGN KEY (dresseurId) REFERENCES Dresseur(id),
    FOREIGN KEY (pokemonId) REFERENCES Pokemon(id)
);

