DROP TABLE IF EXISTS UserH2;

CREATE SEQUENCE "USERS_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE UserH2 (
    id BIGINT NOT NULL DEFAULT nextval('USERS_SEQ') PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    experience INTEGER NOT NULL,
    gold INTEGER NOT NULL,
    levels INTEGER NOT NULL
);