DROP TABLE IF EXISTS EGGS;
DROP TABLE IF EXISTS POKEMONS;
DROP TABLE IF EXISTS USERS;



CREATE TABLE EGGS(
    id INTEGER NOT NULL,
    userid INTEGER NOT NULL,
    name VARCHAR(20) NOT NULL
);
CREATE TABLE POKEMONS(
    id INTEGER NOT NULL,
    userid INTEGER NOT NULL,
    name VARCHAR(20) NOT NULL,
    xp INTEGER NOT NULL,
    type VARCHAR(20) NOT NULL,
    life_point INTEGER NOT NULL,
    combat_point INTEGER NOT NULL
);
CREATE TABLE USERS(
    id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    gold INTEGER NOT NULL

);
